[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd spotify-sheet-player/backend && npm ci --production=false"]

[phases.build]
cmds = ["cd spotify-sheet-player/backend && npm run build"]

[start]
cmd = "cd spotify-sheet-player/backend && npm start"